services:
  web:
    image: php:apache
    container_name: php_apache_redbean
    ports:
      - "80:80"
    volumes:
      - ./php:/var/www/html
    depends_on:
      - db
    command: /bin/sh -c "apt-get update && apt-get install -y libmariadb-dev && docker-php-ext-install pdo pdo_mysql mysqli && curl -L https://redbeanphp.com/downloadredbeanversion.php?f=all-drivers -o redbeanphp.tar.gz && tar -xvzf redbeanphp.tar.gz -C /var/www/html/ && rm redbeanphp.tar.gz && apache2-foreground"

  db:
    image: mysql:latest
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - db

volumes:
  db_data:
