### GET ip
GET http://localhost:8080/ip

### GET headers
GET http://localhost:8080/headers

### Basic Auth
GET http://localhost:8080/basic-auth/hans/tester
Authorization: Basic aGFuczp0ZXN0ZXI=

### Cookies
GET http://localhost:8080/cookies

### Set Cookies
GET http://localhost:8080/cookies/set?name=foo

### POST
POST localhost:8080/post
Content-Type: application/json

{
  "foo": "bar"
}

